# Generated by Django 4.0.3 on 2022-03-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teeth_model',
            table='teeth',
        ),
    ]
